# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Colin's Blog"

author:
  facebook:         niloc2colin
  youtubeUser:      your-id
  youtubeChannel:   your-id
  twitter:          kw_on
  github:           algamza
  stackoverflow:    your-id
  quora:            your-id
  linkedin:         kim-kwonsik-a3489517
  pinterest:        your-id
  googlePlus:       algamza1
  instagram:        niloc2colin
  reddit:           your-id
  medium:           your-id
  tumblr:           your-id
  email:            algamza1@gmail.com

copyright:
  year:             2018
  name:             Colin

# Google-analytics
google-analytics:
  id:               "algamza1"

# Disqus
disqus:
  id:               "algamza"

# URL
url:                "https://algamza.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/algamza/algamza.github.io"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]